### PR TITLE
Header extension

### PR DESCRIPTION
**Pull request by AlanKuurstra**

### CODE REVIEW

**Comment by AlanKuurstra** [comment]
currently compiling, but fails tests. not ready to merge.

tests fail due to this line in ismrmrd.cpp :
#define vector_cmp_limit(a, b, c) memcmp(a, b, sizeof(*a) * c)

**Comment by mklassen** [comment]
Try adding quotes around the a in sizeof

```
#define vector_cmp_limit(a, b, c) memcmp(a, b, sizeof(*(a)) * (c))
```

**Comment by AlanKuurstra** [comment]
testing in ice, not yet ready to merge.

**Comment by AlanKuurstra** [comment]
ice complains that it cannot find stdint.h

**Comment by AlanKuurstra** [comment]
the library is currently compiling in vs2008. However, in ice there are redefinition errors since ice must also solve the stdint.h problems with vs2008.  

Their type definitions live in MrBasicTypes.h

I could guard the new ismrmrd types header (vstypes.h) with an
ifndef _MRCOMMON_GLOBALDEFINITIONS_MRBASICTYPES_H

but it's ugly to have an ice variable in ismrmrd and also ice projects would have to be careful to only include ismrmrd after MrBasicTypes.h

probably I'll just make a new preprocessor flag ISMRMRD_EXTERNAL_STDINT_TYPES in ismrmrd to guard against redefinitions

**Comment by AlanKuurstra** [comment]
The library works with ice.

**Comment by AlanKuurstra** [comment]
the ISMRMRD_EXTERNAL_STDINT_TYPES flag was removed. the redefinition error is avoided if the types are defined the same in MrBasicTypes.h and vstypes.h

**Pull request merged**
